version: '3'
networks:
  team:
    external: true
services:
  app:
    container_name: 'team-service'
    image: node:16
    working_dir: /usr/src/app
    restart: always
    command: yarn start:dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=${PORT}
    networks:
      - team
    depends_on:
      - app_database
    links:
      - app_database
  #Database app
  app_database:
    container_name: 'team-dev-db'
    image: 'postgres:latest'
    restart: always
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teams
    networks:
      - team
volumes:
  pg_data:
  